# Patch badge_combined.svg (generated by ReportGenerator 5.5.10.0) to:
# 1. Widen left section by 10px for longer metric labels
# 2. Cycle "Coverage" text through Line/Branch/Method/Full Coverage
#
# NOTE: This script targets ReportGenerator 5.5.10.0 SVG output format.
# Upgrading ReportGenerator may change SVG paths/coordinates and cause
# replacement patterns to fail silently — update patterns accordingly.
param()

$badgePath = Join-Path $PSScriptRoot "..\badges\badge_combined.svg"
if (-not (Test-Path $badgePath)) {
    throw "Badge file not found: $badgePath — reportgenerator may have failed or changed output format."
}
$fullPath = Resolve-Path $badgePath
$content = [System.IO.File]::ReadAllText($fullPath.Path)

# Track warnings for replacements that didn't match
$script:replacementWarnings = @()
$script:totalReplaceCalls = 0

function SafeReplace([string]$text, [string]$old, [string]$new) {
    $script:totalReplaceCalls++
    $result = $text.Replace($old, $new)
    if ($result -ceq $text) {
        $script:replacementWarnings += "Pattern not found (skipped): '$old'"
    }
    return $result
}

# ======== 1. Widen the overall SVG (155 -> 165) ========
# Blanket replace handles all width="155" occurrences including rect elements and masks
$content = SafeReplace $content 'width="155"' 'width="165"'

# ======== 2. Reshape sections: widen gray, shift red+green right ========
$content = SafeReplace $content '<rect x="0" y="0" width="90" height="20" fill="#444"/>' `
                                    '<rect x="0" y="0" width="100" height="20" fill="#444"/>'
$content = SafeReplace $content '<rect x="90" y="0" width="20" height="20" fill="#c00"/>' `
                                    '<rect x="100" y="0" width="20" height="20" fill="#c00"/>'
$content = SafeReplace $content '<rect x="110" y="0" width="45" height="20" fill="#00B600"/>' `
                                    '<rect x="120" y="0" width="45" height="20" fill="#00B600"/>'

# ======== 3. Shift text positions ========
$content = SafeReplace $content 'x="132.5" y="15"' 'x="142.5" y="15"'
$content = SafeReplace $content 'x="132.5" y="14"' 'x="142.5" y="14"'

# ======== 4. Shift hover/title overlay rects ========
$content = SafeReplace $content 'x="90" y="0" width="65" height="20" fill-opacity="0">' `
                                    'x="120" y="0" width="45" height="20" fill-opacity="0">'

# ======== 5. Shift icon paths right by +10 ========

# 5a. Line coverage icon — three horizontal lines
$content = SafeReplace $content 'M94 6.5 h12 M94 10.5 h12 M94 14.5 h12' `
                                    'M104 6.5 h12 M104 10.5 h12 M104 14.5 h12'

# 5b. Branch coverage icon — shift first relative-to-origin m
$content = SafeReplace $content 'm 97.627847,15.246584 q' `
                                    'm 107.627847,15.246584 q'

# 5c. Method coverage icon
$content = SafeReplace $content 'm 100.5384,15.628605 5.3846,-2.9363' `
                                    'm 110.5384,15.628605 5.3846,-2.9363'
# Absolute M with implicit lineto pairs — shift all x coords
$content = SafeReplace $content `
    'M 100,8.350955 105.8726,6.213935 100,4.076925 94.1274,6.213935 Z m 7,-2.12019' `
    'M 110,8.350955 115.8726,6.213935 110,4.076925 104.1274,6.213935 Z m 7,-2.12019'
# Absolute Q in method path
$content = SafeReplace $content `
    'Q 93.3028,13.491585 93.1514,13.239175 93,12.986775 93,12.692305' `
    'Q 103.3028,13.491585 103.1514,13.239175 103,12.986775 103,12.692305'
$content = SafeReplace $content 'Q 107,5.894225 107,6.230765 Z' `
                                    'Q 117,5.894225 117,6.230765 Z'

# 5d. Full method coverage icon
$content = SafeReplace $content 'm 107,6.230765 v 6.46154' `
                                    'm 117,6.230765 v 6.46154'
# Absolute C in fullmethod path
$content = SafeReplace $content `
    'C 93.389767,13.539262 93.252333,13.407448 93.1514,13.239175 93.050467,13.070908 93,12.888618 93,12.692305' `
    'C 103.389767,13.539262 103.252333,13.407448 103.1514,13.239175 103.050467,13.070908 103,12.888618 103,12.692305'

# 5e. Full method coverage — extra lines (with style attr)
$content = SafeReplace $content 'm 100.0644,16.676777 -0.002,-7.833027 6.90625,-2.546875' `
                                    'm 110.0644,16.676777 -0.002,-7.833027 6.90625,-2.546875'
$content = SafeReplace $content 'M 99.914297,8.7645146 93.052236,5.882392' `
                                    'M 109.914297,8.7645146 103.052236,5.882392'

# ======== 6. Replace static "Coverage" text with animated metric labels ========
$oldLabelShadow = '<text x="53" y="15" fill="#010101" fill-opacity=".3">Coverage</text>'
$newLabelShadow = @'
<text class="linecoverage" x="58" y="15" fill="#010101" fill-opacity=".3" font-size="9">Line Coverage</text><text class="branchcoverage" x="58" y="15" fill="#010101" fill-opacity=".3" font-size="9">Branch Coverage</text><text class="methodcoverage" x="58" y="15" fill="#010101" fill-opacity=".3" font-size="9">Method Coverage</text><text class="fullmethodcoverage" x="58" y="15" fill="#010101" fill-opacity=".3" font-size="9">Full Coverage</text>
'@
$beforeShadow = $content
$content = $content -replace [regex]::Escape($oldLabelShadow), $newLabelShadow
if ($content -eq $beforeShadow) {
    $script:replacementWarnings += "Label shadow pattern not found (skipped): '$oldLabelShadow'"
}

$oldLabelFg = '<text x="53" y="14" fill="#fff">Coverage</text>'
$newLabelFg = @'
<text class="linecoverage" x="58" y="14" fill="#fff" font-size="9">Line Coverage</text><text class="branchcoverage" x="58" y="14" fill="#fff" font-size="9">Branch Coverage</text><text class="methodcoverage" x="58" y="14" fill="#fff" font-size="9">Method Coverage</text><text class="fullmethodcoverage" x="58" y="14" fill="#fff" font-size="9">Full Coverage</text>
'@
$beforeFg = $content
$content = $content -replace [regex]::Escape($oldLabelFg), $newLabelFg
if ($content -eq $beforeFg) {
    $script:replacementWarnings += "Label foreground pattern not found (skipped): '$oldLabelFg'"
}

[System.IO.File]::WriteAllText($fullPath.Path, $content)

$skipped = $script:replacementWarnings.Count
$labelPatterns = 2  # shadow + foreground label checks
$totalReplace = $script:totalReplaceCalls + $labelPatterns

if ($skipped -eq $totalReplace) {
    Write-Warning "All patterns skipped — SVG template may have changed, no modifications applied."
} elseif ($skipped -gt 0) {
    Write-Warning "Badge patched with $skipped/$totalReplace skipped replacement(s) — SVG template may have changed:"
    foreach ($w in $script:replacementWarnings) {
        Write-Warning "  $w"
    }
} else {
    Write-Host "Badge patched: widened to 165px, labels cycle through Line/Branch/Method/Full Coverage"
}
